#!/bin/csh
#

# Generated by CHARMM-GUI (http://www.charmm-gui.org) v3.7

# This folder contains GROMACS formatted force fields, a pre-optimized PDB structure, and GROMACS inputs.
# All input files were optimized for GROMACS 2019.2 or above, so lower version of GROMACS can cause some errors.
# We adopted the Verlet cut-off scheme for all minimization, equilibration, and production steps because it is 
# faster and more accurate than the group scheme. If you have a trouble with a performance of Verlet scheme while 
# running parallelized simulation, you should check if you are using appropriate command line.
# For MPI parallelizing, we recommand following command:
# mpirun -np $NUM_CPU gmx mdrun -ntomp 1

set init = step5_input
set rest_prefix = step5_input
set mini_prefix = step6.0_minimization
set equi_prefix = step6.%d_equilibration
set prod_prefix = step7_production
set rep_info = (pH_0.00 pH_1.00 pH_2.00 pH_3.00 pH_4.00 pH_5.00 pH_6.00 pH_7.00 pH_8.00 pH_9.00 pH_10.00 pH_11.00 pH_12.00 pH_13.00 )


# Minimization
# In the case that there is a problem during minimization using a single precision of GROMACS, please try to use 
# a double precision of GROMACS only for the minimization step.

# Production
set cnt    = 1
set cntmax = 10

while ( ${cnt} <= ${cntmax} )
    @ pcnt = ${cnt} - 1
    foreach i (${rep_info})
        set istep = ${i}_${cnt}
        set pstep = ${i}_${pcnt}
        if ( ${cnt} == 1 ) then
            set pstep = step6.6_equilibration_BUF
            sh sed.sh ${pstep}.gro
            gmx grompp -f ${i}.mdp -o ${i}/${istep}.tpr -c ${pstep}.gro -p topol.top -n index.ndx -maxwarn 999
        else
            sh sed.sh ${pstep}.gro
            gmx grompp -f ${i}.mdp -o ${i}/${istep}.tpr -c ${pstep}.gro -t ${pstep}.cpt -p topol.top -n index.ndx -maxwarn 999
        endif
        gmx mdrun -v -deffnm ${i}/${istep}
        @ cnt += 1
    end
end
